# Generated by Django 5.0.1 on 2024-01-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="formmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=1000)),
                ("last_name", models.CharField(max_length=1000)),
                ("email", models.CharField(max_length=100)),
                ("message", models.TextField(max_length=1000)),
            ],
        ),
    ]
